name: Run Appium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest  # Use Windows instead of Ubuntu

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        shell: cmd
        run: |
          python -m venv C:\environments\appium_env
          C:\environments\appium_env\Scripts\activate
          pip install -r requirements.txt


      - name: Start Appium Server
        shell: cmd
        run: |
          npm install -g appium
          Start-Job -ScriptBlock { appium --log appium.log }


      - name: Run Tests
        shell: cmd
        run: |
          C:\environments\appium_env\Scripts\activate
          python -m pytest tests/


