name: Run Appium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest  # Ensure it's Windows

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Create Virtual Environment and Install Dependencies
        run: |
          python -m venv C:\environments\appium_env
          call C:\environments\appium_env\Scripts\activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest  # Ensure pytest is installed

      - name: Start Appium Server
        run: |
          npm install -g appium
          start /B appium --log appium.log  # Correct way to start Appium in the background

      - name: Run Tests
        shell: cmd
        run: |
          call C:\environments\appium_env\Scripts\activate
          python -m pytest tests/
