name: Run Appium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest  # Use Windows instead of Ubuntu

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m venv C:\environments\appium_env
          C:\environments\appium_env\Scripts\activate
          pip install -r requirements.txt

      - name: Start Appium Server
        run: |
          npm install -g appium
          Start-Process -NoNewWindow -FilePath "appium" -ArgumentList "--log appium.log"
        shell: powershell

      - name: Run Tests
        env:
          APPIUM_SERVER: "http://localhost:4723/wd/hub"
        run: |
          C:\environments\appium_env\Scripts\activate
          pytest tests/
